import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const out=path.resolve('architecture'), prefix='Practica_03/yes_no_app/', stem='yes-no-app-architecture';
fs.mkdirSync(out,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const files=['lib/main.dart','lib/config/theme/app_theme.dart','lib/config/helpers/get_yes_no_answer.dart','lib/domain/entities/message.dart','lib/infrastructure/models/yes_no_model.dart','lib/presentation/providers/chat_provider.dart','lib/presentation/screens/chat/chat_screen.dart','lib/presentation/widgets/shared/message_field_box.dart','lib/presentation/widgets/chat/my_message_bubble.dart','lib/presentation/widgets/chat/her_message_bubble.dart','pubspec.yaml','pubspec.lock','android/app/build.gradle.kts','android/app/src/main/AndroidManifest.xml','web/index.html','windows/CMakeLists.txt'];
const sources=files.map(p=>({path:prefix+p,url:'https://github.com/Brisgregorio/Practicas_DMI_230362/blob/main/'+prefix+p,sha256:hash(fs.readFileSync(p)),lines:fs.readFileSync(p,'utf8').trimEnd().split('\n').length}));
const nodes=[];
function n(id,label,sub,layer,tech,responsibility,file,x,y,type='backend',extra={}){nodes.push({id,label,sublabel:sub,layer,technology:tech,responsibility,file,pos:[30+(x-40)*5/6,y+180],type,...extra});}
n('user','User','Writes a question','Actor','Human','Enters text through the chat interface.',null,40,-100,'external');
n('app','Flutter application','main → MyApp → MaterialApp','Mobile client','Flutter / Dart runtime','runApp starts MyApp. MultiProvider registers ChatProvider; MaterialApp opens ChatScreen.','lib/main.dart',400,80,'frontend');
n('theme','AppTheme','Material 3 · pink seed','Mobile client','Flutter ThemeData','selectedColor: 6 selects pink. Dark brightness is commented out; diagram themes are independent.','lib/config/theme/app_theme.dart',760,80,'frontend');
n('screen','ChatScreen / _ChatView','Chat interface · context.watch','Presentation','Flutter / provider','Scaffold, avatar, message list and input. Watches ChatProvider; selects bubbles using FromWho.','lib/presentation/screens/chat/chat_screen.dart',40,280,'frontend');
n('input','MessageFieldBox','TextEditingController · FocusNode','Presentation','Flutter TextFormField','Submit or send button clears text and calls onValue. Controllers are created in build; no disposal is implemented.','lib/presentation/widgets/shared/message_field_box.dart',400,280,'frontend');
n('state','ChatProvider','sendMessage · herReply','State management','Provider / ChangeNotifier','Empty string returns. Adds user Message to messageList. Only text.endsWith("?") invokes herReply (not awaited). notifyListeners rebuilds UI; 100 ms delay then 300 ms animateTo bottom. No try/catch.','lib/presentation/providers/chat_provider.dart',760,480);
n('list','messageList / ListView','User + response messages','Presentation / state','List<Message> / ListView.builder','ChatProvider owns the list (two initial user messages). ListView reads it and uses chatScrollController. notifyListeners refreshes the list.','lib/presentation/screens/chat/chat_screen.dart',400,480,'frontend');
n('mine','MyMessageBubble','message.text','Presentation','Flutter Widget','Renders user Message text with primary theme color.','lib/presentation/widgets/chat/my_message_bubble.dart',40,480,'frontend');
n('http','GetYesNoAnswer / Dio','Random choice → GET ?force=…','Infrastructure (config/helpers)','Dio / dart:math Random','nextInt(100): yes 40%, no 40%, maybe 20%. Derives Spanish text locally and requests matching force value. The user question is NOT sent. Reads only response.data["image"] as String; ignores API answer.','lib/config/helpers/get_yes_no_answer.dart',760,700);
n('api','Yes/No API','https://yesno.wtf/api','External API / public internet','HTTPS / JSON','GET with force=yes|no|maybe. HTTP response is untrusted. No live request was made; actual returned image host is unknown.',null,1120,700,'external',{url:'https://yesno.wtf/api'});
n('mapping','Direct Message mapping','Local text + response image','Infrastructure → domain','Dart Message constructor','Actual path: Message(text: answerForChat, fromWho: hers, imageUrl: response.data["image"] as String). The force parameter intends agreement, but response answer is neither read nor validated.','lib/config/helpers/get_yes_no_answer.dart',760,920);
n('entity','Message / FromWho','text · imageUrl? · sentAt','Domain','Dart class / enum','One Message holds text, nullable imageUrl, FromWho.me/hers and sentAt. No Yes/No/Maybe enum exists. Same object reaches the text and image widgets.','lib/domain/entities/message.dart',400,920);
n('hers','HerMessageBubble','Text + _ImageBubble','Presentation','Flutter / Image.network','Reads message.text and message.imageUrl! from the same object. loadingBuilder shows image-loading text; no errorBuilder or URL validation.','lib/presentation/widgets/chat/her_message_bubble.dart',40,920,'frontend');
n('image','External GIF / image','Dynamic response image URL','External image resource / internet','Image.network','Image URL comes from response.data["image"]. Host cannot be established statically; no invented host or example URL.',null,1120,1150,'external');
n('model','YesNoModel (unused)','fromJsonMap → toMessageEntity','Infrastructure / inactive','Dart JSON model','Defines answer, forced, image; fromJsonMap and toJson. No import/call from live request path. toMessageEntity maps yes to Si, all other answers (including maybe) to No. No field validation.','lib/infrastructure/models/yes_no_model.dart',400,1150);
n('avatar','External avatar','encrypted-tbn0.gstatic.com','External image resource / internet','NetworkImage','Separate static avatar URL in ChatScreen; unrelated to answer GIF.',null,1120,280,'external',{url:fs.readFileSync('lib/presentation/screens/chat/chat_screen.dart','utf8').match(/https:\/\/[^']+/)[0]});
n('sdk','Flutter SDK / Dart','pubspec.yaml + pubspec.lock','Development','Flutter SDK / Dart ^3.13.2','Runtime: flutter, cupertino_icons, provider, dio. Dev: flutter_test, flutter_lints, flutter_launcher_icons. Lockfile and local package configuration inspected; no package installation performed.','pubspec.yaml',40,1430);
n('targets','Development targets','Android · Web · Windows','Development','Gradle / HTML / CMake','Verified Android Flutter plugin, web bootstrap and Windows CMake target. iOS, Linux and macOS directories also exist. Android main manifest does not declare INTERNET; no configuration changed.','android/app/build.gradle.kts',400,1430);
n('git','Git working tree','Versioned project sources','Source control','Git','Local checkout identity and existing dirty generated plugin files recorded. This task writes architecture artifacts only; no commit, push or publication performed.','pubspec.yaml',760,1430);
n('github','GitHub repository','main · requested source links','Source control / GitHub boundary','GitHub','Brisgregorio/Practicas_DMI_230362. Source URLs use main and verified local repository-relative paths. Remote branch contents were not fetched.','pubspec.yaml',1120,1430,'external');
const edges=[];const e=(from,to,label,variant='default')=>edges.push({id:from+'-'+to,from,to,label,variant});
e('user','screen','Enter text','emphasis');e('app','screen','home');e('app','theme','theme');e('screen','input','onValue','emphasis');e('input','state','sendMessage','emphasis');e('state','list','add / notify','emphasis');e('list','mine','FromWho.me');e('state','http','endsWith(?)','emphasis');e('http','api','GET force','emphasis');e('api','mapping','JSON image','emphasis');e('http','mapping','local text','emphasis');e('mapping','entity','construct','emphasis');e('entity','hers','same Message','emphasis');e('hers','image','GET image URL');e('screen','avatar','avatar fetch');e('sdk','targets','build');e('git','github','source links','dashed');
Object.assign(edges.find(e=>e.id==='input-state'),{fromSide:'right',toSide:'top'});
const candidate={schema_version:1,diagram_type:'architecture',meta:{title:'Práctica 03 - Yes No App',output:'architecture/archify/yes-no-app-architecture.html',quality_profile:'showcase',locale:'en',repository:{url:execFileSync('git',['remote','get-url','origin'],{encoding:'utf8'}).trim(),revision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),provider:'github'}},components:nodes.map(({id,label,sublabel,pos,type,file})=>({id,label,sublabel,pos,type,size:[210,78],...(file?{sources:[{path:prefix+file,line:1,end_line:sources.find(s=>s.path===prefix+file).lines,label:'Open source code'}]}:{})})),connections:edges,boundaries:[{kind:'region',label:'Internal Flutter application · mobile client',wraps:['app','theme','screen','input','state','list','mine','http','mapping','entity','hers','model'],pad:22},{kind:'security-group',label:'External API · public internet',wraps:['api'],pad:24},{kind:'security-group',label:'External image resource',wraps:['image'],pad:24},{kind:'region',label:'Development infrastructure',wraps:['sdk','targets'],pad:20},{kind:'security-group',label:'GitHub source-control boundary',wraps:['github'],pad:20}],cards:[{dot:'amber',title:'Verified behavior / requirement gap',items:['The app chooses text locally and sends force to the API. It does not derive text from the returned answer.','One Message preserves text/image pairing, but API agreement is not validated. YesNoModel is unused.']},{dot:'rose',title:'Not implemented',items:['HTTP error handling, response field validation, image URL validation and image errorBuilder.','Fallback reply, API loading state, retry and error recovery. No answer-value enum.']},{dot:'cyan',title:'Implemented guards and loading',items:['Empty string ignored; non-question remains a user message without an API request. Whitespace is not trimmed.','Image loadingBuilder only. notifyListeners and ScrollController refresh and scroll the chat.']}]};
fs.writeFileSync(path.join(out,stem+'.json'),JSON.stringify(candidate,null,2));
fs.writeFileSync(path.join(out,stem+'.sources.json'),JSON.stringify({repository:candidate.meta.repository,sourceBranch:'main',sources,nodes,connections:edges,dirtyPaths:execFileSync('git',['status','--short'],{encoding:'utf8'}),limitations:['No live API response sampled; dynamic image host unknown.','Remote main source contents not fetched.','Answer-from-same-response requirement is not satisfied by existing code.']},null,2));
console.log('Wrote complete candidate and source evidence.');






