import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const dir=path.resolve('architecture'),stem='yes-no-app-architecture';
const data=JSON.parse(fs.readFileSync(path.join(dir,stem+'.sources.json')));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
data.nodes.find(n=>n.id==='sdk').files=['pubspec.yaml','pubspec.lock'];
data.nodes.find(n=>n.id==='targets').files=['android/app/build.gradle.kts','android/app/src/main/AndroidManifest.xml','web/index.html','windows/CMakeLists.txt'];
data.nodes.find(n=>n.id==='list').files=['lib/presentation/screens/chat/chat_screen.dart','lib/presentation/providers/chat_provider.dart'];
const groups={'Mobile client':['app','theme'],'Presentation':['screen','input','list','mine','hers'],'State management':['state'],'Domain':['entity'],'Infrastructure':['http','mapping','model'],'External services':['api','image','avatar'],'Development':['sdk','targets'],'Source control':['git','github']};
let html=fs.readFileSync(path.join(dir,'archify',stem+'.html'),'utf8');
// Keep the original Archify artifact/receipt intact; this is a separately hashed viewer extension.
html=html.replaceAll('/blob/'+data.repository.revision+'/', '/blob/main/');
const style=`<style>
#focus-chip{display:none!important}.architecture-index{margin:20px auto;max-width:1200px;padding:20px;border:1px solid #77889966;border-radius:16px}.architecture-index h2{font-size:18px;margin-bottom:12px}.architecture-layers{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.architecture-layers section{border-left:3px solid #25a7b5;padding-left:10px}.architecture-layers h3{font-size:13px}.architecture-layers button{display:block;text-align:left;background:transparent;color:inherit;border:0;padding:5px 0;cursor:pointer;font:inherit;font-size:12px}.architecture-layers button:hover{text-decoration:underline}.architecture-note{font-size:13px;line-height:1.65;margin:16px 0 0}.component-card{position:fixed;z-index:9999;right:20px;top:90px;width:min(420px,calc(100vw - 40px));max-height:calc(100vh - 120px);overflow:auto;padding:24px;border:1px solid #64748b;border-radius:16px;background:#111c30;color:#edf3ff;box-shadow:0 12px 50px #0007;line-height:1.55;font:14px/1.6 system-ui}.component-card[hidden]{display:none}.component-card h2{font-size:21px;padding-right:20px}.component-card p{margin:12px 0}.component-card code{overflow-wrap:anywhere;font-size:11px}.component-card a{color:#65d7ef}.component-card button{float:right;background:transparent;color:inherit;border:1px solid #778899;padding:4px 9px;border-radius:6px;cursor:pointer}.component-card dt{font-weight:bold;margin-top:12px}.component-card dd{margin:0}.component-card .source{border-top:1px solid #77889955;margin-top:12px;padding-top:10px}[data-theme=light] .component-card{background:white;color:#17233a}[data-theme=light] .component-card a{color:#006679}@media(max-width:700px){.architecture-layers{grid-template-columns:repeat(2,minmax(0,1fr))}}@media print{.component-card{display:none!important}}
</style>`;
const index=`<section class="architecture-index"><h2>Architecture layers · select a component</h2><div class="architecture-layers">${Object.entries(groups).map(([layer,ids])=>`<section><h3>${layer}</h3>${ids.map(id=>`<button data-component="${id}">${esc(data.nodes.find(n=>n.id===id).label)}</button>`).join('')}</section>`).join('')}</div><p class="architecture-note"><strong>Verified request:</strong> User → ChatScreen → MessageFieldBox → ChatProvider → user Message / messageList. Only a trailing “?” triggers GetYesNoAnswer → Dio GET with force → API JSON → direct Message mapping → herReply adds to messageList → HerMessageBubble → Image.network.<br><strong>Association gap:</strong> text is chosen locally (40% yes / 40% no / 20% maybe); force requests a matching image. The API answer is ignored. One Message carries both fields, but agreement is not checked. YesNoModel is unused.<br><strong>Not implemented:</strong> request failure handling, missing-field validation, image URL validation/errorBuilder, fallback reply, API loading state, retry and error recovery. Image loadingBuilder and empty-string/non-question guards are implemented.<br><strong>Trust:</strong> the question stays in the app; force crosses the public internet. Response JSON/image URL and downloaded image bytes are untrusted. Network failures propagate without an application handler. The avatar is a separate static external image.</p></section>`;
html=html.replace('</head>',style+'</head>').replace('<div class="diagram-container"',index+'<div class="diagram-container"');
if(!html.includes('Architecture layers ·'))throw Error('Index insertion anchor missing');
html=html.replace('</body>',`<aside id="component-card" class="component-card" hidden aria-label="Component information" aria-live="polite"></aside><script id="component-evidence" type="application/json">${JSON.stringify(data).replaceAll('<','\\u003c')}</script><script>
(()=>{const data=JSON.parse(document.getElementById('component-evidence').textContent),card=document.getElementById('component-card');const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');let current=null;
function show(id){const n=data.nodes.find(x=>x.id===id);if(!n)return;current=id;const files=n.files|| (n.file?[n.file]:[]);card.dataset.component=id;card.innerHTML='<button id="close-component" aria-label="Close component card">×</button><h2>'+escape(n.label)+'</h2><dl><dt>Architectural layer</dt><dd>'+escape(n.layer)+'</dd><dt>Technology</dt><dd>'+escape(n.technology)+'</dd><dt>Responsibility</dt><dd>'+escape(n.responsibility)+'</dd></dl>'+files.map(file=>{const s=data.sources.find(s=>s.path==='Practica_03/yes_no_app/'+file);return '<div class="source"><code>'+escape(s.path)+'</code><br><a target="_blank" rel="noopener noreferrer" href="'+escape(s.url)+'">Open source code</a></div>'}).join('')+(n.url?'<p><a target="_blank" rel="noopener noreferrer" href="'+escape(n.url)+'">Open external service</a></p>':'')+(n.id==='github'?'<p>Repository: Brisgregorio/Practicas_DMI_230362 · main</p>':'');card.hidden=false;document.getElementById('close-component').onclick=close;}
function close(){current=null;card.hidden=true;Archify.focus.clear();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-component]');if(b){Archify.focus.set(b.dataset.component,{toggle:false});show(b.dataset.component);}const n=e.target.closest('.diagram-container [data-node-id]');if(n)show(n.dataset.nodeId);});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
new MutationObserver(()=>{const active=Archify.focus.active();if(typeof active==='string'&&active!==current)show(active);else if(active===null){current=null;card.hidden=true;}}).observe(document.querySelector('.diagram-container > svg'),{subtree:true,attributes:true,attributeFilter:['data-focus-selected']});
window.architectureDetails={show,close};})();
</script></body>`);
fs.writeFileSync(path.join(dir,stem+'.html'),html);
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const checks=data.sources.map(s=>({path:s.path,exists:fs.existsSync(s.path.replace('Practica_03/yes_no_app/','')),hashUnchanged:hash(fs.readFileSync(s.path.replace('Practica_03/yes_no_app/','')))===s.sha256,url:s.url,embedded:html.includes(s.url),validUrl:s.url==='https://github.com/Brisgregorio/Practicas_DMI_230362/blob/main/'+s.path}));
if(checks.some(s=>!s.exists||!s.hashUnchanged||!s.embedded||!s.validUrl))throw Error('Source validation failed');
fs.writeFileSync(path.join(dir,stem+'.source-check.json'),JSON.stringify({status:'pass',checks,api:'https://yesno.wtf/api',sameResponseAnswer:false,association:'local answer → force request → returned image; same Message, no answer validation'},null,2));
console.log('Enhanced viewer and source checks written.');
